#!/usr/bin/env python3
"""
NoirSec Differential Witness Tester
=====================================
Runs two circuit versions (vulnerable + patched) against the same inputs
and reports divergence -- inputs accepted by one but not the other.

Usage:
  # Single pair:
  python3 detection/noir_diff_test.py \\
    --vulnerable vulnerabilities/01-under-constrained/UC01-missing-range-check/vulnerable \\
    --patched    vulnerabilities/01-under-constrained/UC01-missing-range-check/patched \\
    --iterations 50

  # Batch scan all vuln/patched pairs:
  python3 detection/noir_diff_test.py --scan-all vulnerabilities/

Limitations (documented honestly):
  - Cannot detect privacy leaks (use privacy_leak_fuzzer.py)
  - Cannot detect logic errors where both versions accept/reject identically
  - Random input generation may miss vulnerabilities requiring specific trigger values
  - This is a fuzzer, not a formal verifier; absence of findings != secure
  - Requires nargo in PATH (set export PATH="$HOME/.nargo/bin:$PATH" on WSL)
"""

import argparse
import subprocess
import sys
import os
import re
import random
import json
import tempfile
import shutil
from typing import Optional, Dict, List, Tuple

# BN254 prime
P = 21888242871839275222246405745257275088548364400416034343698204186575808495617

# ── TOML parsing ──────────────────────────────────────────────────────────────

def parse_prover_toml(path: str) -> Dict[str, str]:
    """Parse Prover.toml to extract field names and their current values."""
    fields = {}
    if not os.path.exists(path):
        return fields
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key:
                fields[key] = value
    return fields


def infer_type(field_name: str, value: str) -> str:
    """Heuristically infer the type of a field from its name and value."""
    name_lower = field_name.lower()
    # Detect public/commitment fields (don't fuzz these -- they're derived)
    if any(k in name_lower for k in ["hash", "commit", "null", "slot", "root"]):
        return "derived"
    # Detect small integer fields
    if any(k in name_lower for k in ["age", "min", "max", "flag", "bracket", "choice"]):
        return "small_int"
    # Detect u64-like balance/amount fields
    if any(k in name_lower for k in ["balance", "amount", "value", "count", "total"]):
        return "u64"
    # Default: Field element
    return "field"


# ── Input generation ──────────────────────────────────────────────────────────

def generate_inputs(schema: Dict[str, str], seed: Optional[int] = None) -> Dict[str, str]:
    """Generate one set of test inputs based on field schema."""
    if seed is not None:
        random.seed(seed)

    result = {}
    for key, value in schema.items():
        field_type = infer_type(key, value)
        if field_type == "derived":
            result[key] = value  # keep original derived values
        elif field_type == "small_int":
            result[key] = str(random.randint(0, 255))
        elif field_type == "u64":
            result[key] = str(random.randint(0, 2**64 - 1))
        else:
            result[key] = str(random.randint(0, P - 1))
    return result


def adversarial_inputs(schema: Dict[str, str]) -> List[Dict[str, str]]:
    """Generate a set of known-adversarial inputs that probe boundary conditions."""
    boundary_values = [
        ("zero", "0"),
        ("one", "1"),
        ("max_u8", "255"),
        ("max_u32", "4294967295"),
        ("max_u64", "18446744073709551615"),
        ("field_prime_minus_1", str(P - 1)),
        ("field_prime_minus_2", str(P - 2)),
        ("large_field", str(P // 3)),
        ("two_pow_128", str(2**128)),
        ("two_pow_64_plus_1", str(2**64 + 1)),
    ]

    inputs = []
    for label, bval in boundary_values:
        candidate = {}
        for key, value in schema.items():
            ft = infer_type(key, value)
            if ft == "derived":
                candidate[key] = value  # keep derived values unchanged
            else:
                candidate[key] = bval
        inputs.append((label, candidate))
    return inputs


# ── Nargo execution ───────────────────────────────────────────────────────────

def run_circuit(circuit_dir: str, inputs: Dict[str, str]) -> bool:
    """
    Write inputs to a temp Prover.toml, run nargo execute, return True if proof succeeds.
    """
    if not os.path.exists(os.path.join(circuit_dir, "Nargo.toml")):
        return False

    # Write a temporary Prover.toml
    toml_content = "# Generated by noir_diff_test.py\n"
    for key, val in inputs.items():
        toml_content += f'{key} = "{val}"\n'

    prover_path = os.path.join(circuit_dir, "Prover.toml")
    backup_path = prover_path + ".diff_backup"

    # Backup original
    if os.path.exists(prover_path):
        shutil.copy2(prover_path, backup_path)

    try:
        with open(prover_path, "w") as f:
            f.write(toml_content)

        result = subprocess.run(
            ["nargo", "execute"],
            cwd=circuit_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return "Circuit witness successfully solved" in result.stdout
    except subprocess.TimeoutExpired:
        return False
    except FileNotFoundError:
        print("ERROR: nargo not found. Run: export PATH=\"$HOME/.nargo/bin:$PATH\"")
        sys.exit(1)
    finally:
        # Restore original Prover.toml
        if os.path.exists(backup_path):
            shutil.move(backup_path, prover_path)
        elif not os.path.exists(prover_path):
            # Was never there; remove the test file
            if os.path.exists(prover_path):
                os.remove(prover_path)


def get_gate_count(circuit_dir: str) -> Optional[int]:
    """Get ACIR gate count for a circuit."""
    try:
        result = subprocess.run(
            ["nargo", "info"],
            cwd=circuit_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = result.stdout + result.stderr
        numbers = re.findall(r"\b(\d{1,6})\b", output)
        if numbers:
            return int(numbers[0])
    except Exception:
        pass
    return None


# ── Single pair differential test ────────────────────────────────────────────

def run_diff_test(
    vuln_dir: str,
    patch_dir: str,
    iterations: int = 50,
    label: str = "",
) -> Dict:
    """
    Run differential testing between vulnerable and patched circuits.
    Returns a result dict with findings.
    """
    prover_path = os.path.join(vuln_dir, "Prover.toml")
    schema = parse_prover_toml(prover_path)
    if not schema:
        return {"error": f"No Prover.toml found at {prover_path}"}

    under_constrained = []   # vuln PASS, patch FAIL
    over_constrained = []    # vuln FAIL, patch PASS
    both_pass = 0
    both_fail = 0

    # 1. Adversarial boundary inputs
    for adv_label, inputs in adversarial_inputs(schema):
        v = run_circuit(vuln_dir, inputs)
        p = run_circuit(patch_dir, inputs)
        if v and not p:
            under_constrained.append({"label": f"adversarial:{adv_label}", "inputs": inputs})
        elif not v and p:
            over_constrained.append({"label": f"adversarial:{adv_label}", "inputs": inputs})
        elif v and p:
            both_pass += 1
        else:
            both_fail += 1

    # 2. Random inputs
    for i in range(iterations):
        inputs = generate_inputs(schema, seed=i)
        v = run_circuit(vuln_dir, inputs)
        p = run_circuit(patch_dir, inputs)
        if v and not p:
            under_constrained.append({"label": f"random:{i}", "inputs": inputs})
        elif not v and p:
            over_constrained.append({"label": f"random:{i}", "inputs": inputs})
        elif v and p:
            both_pass += 1
        else:
            both_fail += 1

    # Gate counts
    vuln_gates = get_gate_count(vuln_dir)
    patch_gates = get_gate_count(patch_dir)

    return {
        "label": label,
        "vuln_dir": vuln_dir,
        "patch_dir": patch_dir,
        "iterations": iterations + len(adversarial_inputs(schema)),
        "under_constrained": under_constrained,
        "over_constrained": over_constrained,
        "both_pass": both_pass,
        "both_fail": both_fail,
        "vuln_gates": vuln_gates,
        "patch_gates": patch_gates,
    }


# ── Reporting ─────────────────────────────────────────────────────────────────

def print_report(result: Dict) -> None:
    """Print a human-readable differential test report."""
    label = result.get("label", "")
    print(f"\nDIFFERENTIAL TESTING REPORT: {label}")
    print("=" * 60)
    print(f"Vulnerable:  {result['vuln_dir']}")
    print(f"Patched:     {result['patch_dir']}")
    print(f"Iterations:  {result['iterations']}")
    print()

    uc = result["under_constrained"]
    oc = result["over_constrained"]

    if uc:
        print(f"UNDER-CONSTRAINED SIGNALS: {len(uc)} divergent input(s)")
        print("  (Vulnerable PASSES, Patched FAILS -- patch added missing constraint)")
        for finding in uc[:3]:  # show up to 3
            print(f"\n  [{finding['label']}]")
            for k, v in finding["inputs"].items():
                val_str = str(v)[:60]
                print(f"    {k} = {val_str}")
        if len(uc) > 3:
            print(f"  ... and {len(uc) - 3} more")
        print()

    if oc:
        print(f"OVER-CONSTRAINED SIGNALS: {len(oc)} divergent input(s)")
        print("  (Vulnerable FAILS, Patched PASSES -- patch relaxed a constraint)")
        for finding in oc[:3]:
            print(f"\n  [{finding['label']}]")
            for k, v in finding["inputs"].items():
                val_str = str(v)[:60]
                print(f"    {k} = {val_str}")
        if len(oc) > 3:
            print(f"  ... and {len(oc) - 3} more")
        print()

    print(f"Both pass: {result['both_pass']}  Both fail: {result['both_fail']}")

    # Gate count diff
    vg = result["vuln_gates"]
    pg = result["patch_gates"]
    if vg is not None and pg is not None:
        diff = pg - vg
        pct = (diff / max(vg, 1)) * 100
        print(f"\nCONSTRAINT DIFF:")
        print(f"  Vulnerable: {vg} gates")
        print(f"  Patched:    {pg} gates")
        print(f"  Delta:      {diff:+d} gates ({pct:+.1f}%)")

    print()
    if uc:
        print("VERDICT: HIGH CONFIDENCE -- vulnerable circuit is under-constrained")
        print("  The patched version adds constraints that reject adversarial inputs.")
    elif oc:
        print("VERDICT: OVER-CONSTRAINED SIGNAL -- patched version accepts more inputs")
        print("  The vulnerable version may have been too restrictive (OC pattern).")
    elif result["both_fail"] > result["both_pass"]:
        print("VERDICT: NO DIVERGENCE (most inputs fail both -- may need Prover.toml tuning)")
    else:
        print("VERDICT: NO DIVERGENCE FOUND")
        print("  This does NOT mean the circuit is secure. Manual review is required.")
        print("  Consider:")
        print("  - Privacy leaks (use privacy_leak_fuzzer.py)")
        print("  - Logic errors with identical constraint structure")
        print("  - Inputs requiring domain-specific knowledge to craft")
    print("=" * 60)


# ── Batch scan ────────────────────────────────────────────────────────────────

def scan_all(vulnerabilities_dir: str, iterations: int = 20) -> None:
    """Scan all vuln/patched pairs under vulnerabilities_dir."""
    pairs = []
    for root, dirs, files in os.walk(vulnerabilities_dir):
        if os.path.basename(root) == "vulnerable":
            parent = os.path.dirname(root)
            patched = os.path.join(parent, "patched")
            if os.path.isdir(patched):
                label = "/".join(root.split(os.sep)[-3:-1])
                pairs.append((label, root, patched))

    pairs.sort()
    print(f"\nNoirSec Batch Differential Test")
    print(f"Scanning {len(pairs)} vulnerable/patched pairs...")
    print(f"Iterations per pair: {iterations}")
    print()

    summary = {"under_constrained": [], "over_constrained": [], "clean": []}

    for label, vuln, patch in pairs:
        sys.stdout.write(f"  Testing {label}... ")
        sys.stdout.flush()
        result = run_diff_test(vuln, patch, iterations=iterations, label=label)
        if "error" in result:
            print(f"SKIP ({result['error']})")
            continue

        uc = len(result["under_constrained"])
        oc = len(result["over_constrained"])
        if uc > 0:
            print(f"UC SIGNAL ({uc} inputs)")
            summary["under_constrained"].append(label)
        elif oc > 0:
            print(f"OC SIGNAL ({oc} inputs)")
            summary["over_constrained"].append(label)
        else:
            print("clean")
            summary["clean"].append(label)

    print()
    print("=" * 60)
    print("BATCH SUMMARY")
    print(f"  Under-constrained signals: {len(summary['under_constrained'])}")
    for x in summary["under_constrained"]:
        print(f"    - {x}")
    print(f"  Over-constrained signals:  {len(summary['over_constrained'])}")
    for x in summary["over_constrained"]:
        print(f"    - {x}")
    print(f"  No divergence:             {len(summary['clean'])}")
    print()
    print("NOTE: 'No divergence' does NOT mean secure. See --help for limitations.")
    print("=" * 60)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="NoirSec Differential Witness Tester",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Test a single pair
  python3 detection/noir_diff_test.py \\
    --vulnerable vulnerabilities/01-under-constrained/UC01-missing-range-check/vulnerable \\
    --patched    vulnerabilities/01-under-constrained/UC01-missing-range-check/patched

  # Scan entire vulnerability suite
  python3 detection/noir_diff_test.py --scan-all vulnerabilities/

Limitations:
  - Cannot detect privacy leaks (use privacy_leak_fuzzer.py instead)
  - Cannot detect logic errors where both versions have identical constraints
  - Random fuzzing may miss vulnerabilities needing specific trigger values
  - Not a formal verifier -- absence of findings != the circuit is safe
        """,
    )
    parser.add_argument("--vulnerable", help="Path to vulnerable circuit directory")
    parser.add_argument("--patched", help="Path to patched circuit directory")
    parser.add_argument("--iterations", type=int, default=50,
                        help="Number of random test iterations (default: 50)")
    parser.add_argument("--scan-all", metavar="DIR",
                        help="Scan all vuln/patched pairs under DIR")
    args = parser.parse_args()

    if args.scan_all:
        scan_all(args.scan_all, iterations=args.iterations)
    elif args.vulnerable and args.patched:
        label = os.path.basename(os.path.dirname(args.vulnerable))
        result = run_diff_test(args.vulnerable, args.patched,
                               iterations=args.iterations, label=label)
        if "error" in result:
            print(f"ERROR: {result['error']}")
            sys.exit(1)
        print_report(result)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
